### ISSUE TITLE
If a worker died the log is show as an INFO instead an error or notify

### ISSUE THREAD

**Issue by frsela** [telefonicaid/notification_server#147]
/home/frsela/Datos/ProyectosTID/OpenWebDevice/PUSH_NOTIFICATIONS/notification_server/src/ns_ua/datamanager.js:59
var fullyDisconnected = (Connectors.getConnectorForUAtoken(uatoken).getProtoco
                                                                    ^
TypeError: Cannot call method 'getProtocol' of undefined
    at Object.datamanager.unregisterNode (/home/frsela/Datos/ProyectosTID/OpenWebDevice/PUSH_NOTIFICATIONS/notification_server/src/ns_ua/datamanager.js:59:75)
    at WebSocketConnection.server.onWSRequest.onWSClose (/home/frsela/Datos/ProyectosTID/OpenWebDevice/PUSH_NOTIFICATIONS/notification_server/src/ns_ua/ws_server.js:482:19)
    at WebSocketConnection.EventEmitter.emit (events.js:115:20)
    at WebSocketConnection.handleSocketClose (/home/frsela/Datos/ProyectosTID/OpenWebDevice/PUSH_NOTIFICATIONS/notification_server/node_modules/websocket/lib/WebSocketConnection.js:273:14)
    at CleartextStream.EventEmitter.emit (events.js:85:17)
    at SecurePair.destroy (tls.js:907:22)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
[NS_UA_WS # INFO] - {Wed Dec 12 2012 10:23:46 GMT+0100 (CET) (1355304226561)} - worker 17908 died

**Comment by willyaranda** [comment]
On pull #149
